# fly.toml app configuration file generated for meimuri-blog on 2023-12-30T14:14:41+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "meimuri-blog"
primary_region = "hkg"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
